### ISSUE TITLE
Test from API Console (in the store) cause net::ERR_NAME_NOT_RESOLVED in browser

### ISSUE THREAD

**Issue by K3vin-V** [wso2/docker-apim#52]
I found that the config in the "store" app is wrong and generate "net::ERR_NAME_NOT_RESOLVED" error when you try to call the API through "store/API Console" (fail in pattern 2 / 3 / 4).

- I've try to link the store to the gateway-worker and gateway-manager (external-link in compose) but nothing change
- I've try to modify the "GatewayEndpoint" conf (in "api-manager.xml" of the store, from gateway-worker to gateway-manager cause this endpoints are fronted by the manager) but nothing change,

What do I have to do for correcting this issue ?

**Comment by pubudu538** [comment]
When you are using the API console, the browser does the API invoke. So, this gateway-worker endpoint has to get resolved in your machine. Please add another /etc/hosts entry as below.

127.0.0.1 gateway-worker

This entry is missing in the Readme file (https://github.com/wso2/docker-apim/tree/master/docker-compose/pattern-2). Thank you for bringing this up.

**Comment by K3vin-V** [comment]
Still not working after the modification on the server where I start the docker's container, when I call the worker node :
`[...]$ curl -X GET --header 'Accept: application/json' 'https://gateway-worker:8243/pizzashack/1.0.1/menu' -k
<am:fault xmlns:am="http://wso2.org/apimanager"><am:code>404</am:code><am:type>Status report</am:type><am:message>Not Found</am:message><am:description>The requested resource is not available.</am:description></am:fault>
`
It doesn't work, but when I call the manager one :
`[...]$ curl -X GET --header 'Accept: application/json' 'https://gateway-manager:8243/pizzashack/1.0.1/menu' -k
[{"name":"BBQ Chicken Bacon","description": ...}]`

Where do I have to add the modification you previously list ? Are you sure there's no other modification to do ?

**Comment by pubudu538** [comment]
Based on the shared logs, it looks like API artifact is not synced with gateway-worker node. When you publish an API, API artifact will get created in the gateway-manager node. You can find it in <APIM_HOME>/repository/deployment/server/synapse-configs/default/api/ location. 

Rsync is used to sync API artifacts between gateway-manager and gateway worker nodes. It looks like gateway-worker does not have that API artifact. I hope this works fine in pattern 2 as it is a single node.

**Comment by K3vin-V** [comment]
I'm on pattern 3 and I've tested pattern 2, pattern 3 and 4

**Comment by DilanUA** [comment]
Thanks for your interest in testing out the product. However, we are closing this issue since it relates to an implementation before the re-architecturing of the repository which is no longer supported.
